# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:        christina.kim
email:       'yo@christina.kim'
description: ''
baseurl:     '' # The subpath of your site, e.g. /blog
url:         'https://christina.kim' # The base hostname & protocol for your site
twitter:     'https://www.twitter.com/christinahkim'
github:      'https://www.github.com/christinakim'
instagram:    'https://www.instagram.com/xtkim'
linkedin:     'https://www.linkedin.com/in/chkim1'
rss_feed:         'https://christina.kim/feed.xml'
house: "https://archive.house"
author:
  twitter: christinahkim
disqus:
  shortname: christina-kim

markdown:  kramdown
permalink: pretty
paginate:  10
excerpt_separator: <!--end_excerpt-->

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-feed
  - jekyll-redirect-from

include:
  - _pages
  - htaccess
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

